networks:
  bdr-net:
    driver: overlay
    attachable: true

services:
  # Traefik:
  reverse_proxy:
    image: traefik:v3.3
    # container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--api.insecure=true"
    ports:
      - "80:80"                        # Accès principal (HTTP) → routé vers static + API
      - "8080:8080"                    # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bdr-net

  #  Site web statique:
  static-web:
    image: static-web:latest
    # container_name: static-website --> Interdit
    deploy:
      replicas: 3  # Trois instances pour le site statique
      restart_policy:
        condition: on-failure
    networks:
      - bdr-net
    labels:
      - "traefik.enable=true"

      # toute requête vers http://localhost ira vers ce conteneur
      - "traefik.http.routers.static.rule=Host(`localhost`)"
      - "traefik.http.routers.static.entrypoints=web"

      # Ecoute en interne sur le port 80
      - "traefik.http.services.static.loadbalancer.server.port=80"

      # Configuration pour sticky sessions non-nécessaire

  # Serveur API:
  api-server:
    image: api-server:latest
    # container_name: api-server --> Interdit
    depends_on:
      - postgresql
    deploy:
      replicas: 3  # Trois instances pour le site API
      restart_policy:
        condition: on-failure
    networks:
      - bdr-net
    labels:
      - "traefik.enable=true"

      # toute requête arrivant sur http://localhost/api ira vers ce conteneur
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"

      # Ecoute en interne sur le port 80
      - "traefik.http.services.api.loadbalancer.server.port=80"

      # Configuration pour Sticky sessions (à base de cookies)
      - "traefik.http.services.api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.api.loadbalancer.sticky.cookie.name=api-session"

  # Base de donnée - Suivi_dietetique:
  postgresql:
    image: 'bitnami/postgresql:17'
    # container_name: bdr-postgresql
    environment:
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - .:/data:ro
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bdr-net
