entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true

certificatesResolvers:
  default:
    acme:
      email: admin@test.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
